apiVersion: v1
kind: Service
metadata:
  name: crawler-master-service
  namespace: crawler
spec:
  selector:
    app: crawler-master
  ports:
  - port: 5001
    targetPort: 5001
    protocol: TCP
    name: api
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: crawler-master-external
  namespace: crawler
spec:
  selector:
    app: crawler-master
  ports:
  - port: 80
    targetPort: 5001
    protocol: TCP
    name: http
  type: LoadBalancer  # Change to NodePort if not using cloud provider