apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: "21c464ab-7c6b-4d7c-894b-4134ebf95cd0"
  name: crawler-sa
  namespace: crawler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: crawler-pod-reader
  namespace: crawler
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: crawler-pod-reader-binding
  namespace: crawler
subjects:
- kind: ServiceAccount
  name: crawler-sa
  namespace: crawler
roleRef:
  kind: Role
  name: crawler-pod-reader
  apiGroup: rbac.authorization.k8s.io
